### PR TITLE
Add pulsar

### PR DESCRIPTION
**Pull request by skothari-tibco**

### CODE REVIEW

**Comment by mellistibco** [comment]
Should we be using a connection object rather than just having the url, auth token, etc under settings?

**Comment by skothari-tibco** [comment]
We can; I'll add that.

**Comment by skothari-tibco** [comment]
I used Kafka as an example. Even though we have other Kafka contrib using connections , this contrib does not . But I'm also open to add connection object.

**Comment by mellistibco** [comment]
I think we should start using the connection object, that will enable people to use shared connection settings in the future.

**Comment by vijaynalawade** [comment]
@mellistibco : Do you think we should follow MongoDB like structure for Messaging contributions?

**Comment by mellistibco** [comment]
@vijaynalawade probably :)

**Comment by vijaynalawade** [comment]
@skothari-tibco: Can you please do that then?

**Comment by mellistibco** [comment]
Let's create a new repo called `messaging-contrib`? @fm-tibco

**Comment by fm-tibco** [comment]
Yeah, we can also move kafka there... we can deprecate the contrib one.

**Pull request closed without merging**
